Attribute VB_Name = "MODvariaveis"
Public codjogador As String
Public codfuncionario As String
Public endip As String
Public admin As String
Public nroClientes As Long
Public ip() As String
Public hora As String
Public min As String
